config/routes.rb
NiftyGifter::Application.routes.draw do 

  resources :token, :only => [:create, :destroy]

  resources :events do 
    resources :recipients, :controller => "events"
  end

  resources :recipients do 
    get 'checkout' => 'recipients#checkout'
  end


  resources :scans do
    resources :recipients, :controller => "scans", :except => [:show] 
  end
  match '/events/new/recipient/:recipient_id' => 'events#new', :via => 'get', :as => :new_event_with_recipient
  match '/scans/find/:upc' => 'scans#find', :via => 'get'
  match '/scans/:scan_id/recipients/:id(.:format)' => 'scans#update', :via => 'get'




  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do    
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    match 'auth/:provider/callback', to: 'users/omniauth_callbacks#facebook'
    get '/login' => 'devise/sessions#new', :as => :app_root
    get '/logout' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

end

app/models/scan.rb
class Scan < ActiveRecord::Base
  default_scope order('created_at desc')
  belongs_to :user
  belongs_to :recipient

  validates_presence_of :upc

  accepts_nested_attributes_for :recipient

  attr_accessible :user_id, :recipient_id, :upc, :recipient_attributes


  def get_response
  	if(self.upc.length == 13)
  		Amazon::Ecs.item_lookup(self.upc, {:id_type => "EAN", :search_index => 'All', :response_group => 'Large, Images'})
  	else
      Amazon::Ecs.item_lookup(self.upc, {:id_type => "UPC", :search_index => 'All', :response_group => 'Large, Images'})
    end

  end

end

app/controllers/scans_controller.rb
class ScansController < InheritedResources::Base
	before_filter :authenticate_user! 

	def show
		@scan = current_user.scans.find(params[:id])
	end

	def index
		@scans = current_user.scans.limit(10)
	end

	#/scans/:scan_id/recipients/new - get
	def new
		@scan = current_user.scans.build
		@scan.upc = params[:scan_id]
		@response = @scan.get_response
		@new_recipient = @current_user.recipients.build		
		@recipients = @current_user.recipients
	end

	#post from /scans/:scan_id/recipients/new
	def create
		@scan = current_user.scans.build(:upc => params[:scan_id])
		@recipient = current_user.recipients.create(params[:recipient])
		@scan.recipient = @recipient
		@scan.save!
		redirect_to recipient_path(@scan.recipient.id)
	end

	#put from /scans/123/recipients/new
	def update
		@scan = current_user.scans.build(:upc => params[:scan_id])
		@recipient = current_user.recipients.find(params[:id])
		@scan.recipient = @recipient
		@scan.save!
		redirect_to recipient_path(@scan.recipient.id)
	end

	def destroy  
		@scan = current_user.scans.find(params[:id])
		@scan.destroy  
		respond_to do |format|  
			format.html { redirect_to(scans_url) }  
			format.js   { render :nothing => true }  
		end 
	end
	
	#/scans/find/:upc
	def find
		@scan = current_user.scans.build
		@scan.upc = params[:upc]
		@res = @scan.get_response
	end

end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/scans/find.html.erb
<% if @res.has_error? %>
	<strong><%=@res.error%></strong>
<% else %>

<div class=" pagination-centered">
	<img class="img-polaroid large-image" src=<%= @res.items.first.get('LargeImage/URL')%>>
</div>
<hr/>
<div class="spacer-10"></div>
<div class="add-image-wrap">
	<div class=" pagination-right pull-right">
		<a id="add" href=<%= new_scan_recipient_path(@scan.upc)  %>>
			<img  class="plus-images" src=<%=image_path("plus.png")%>>
		</a>
	</div>
	<div class="pagination-left">
		<a class="muted lead" href=<%=@res.items.first.get('DetailPageURL')%>/><%= @res.items.first.get('ItemAttributes/Title').truncate(40)%></a> <br/>
		<h3><%= @res.items.first.get('OfferSummary/LowestNewPrice/FormattedPrice')%></h3>
	</div>
</div>

<% end %>

app/views/scans/index.html.erb
<div class="width-100 pagination-centered">
  <h3>Saved Items</h3>
</div>

<% current_user.scans.limit(10).order("created_at DESC").each do |scan| %>
<% @scan = scan %>
<%= render 'layouts/scan-list' %>
<%end%>

<%= render 'layouts/scan-links' %>

app/views/scans/new.html.erb
<div class="pagination-centered">
	<h3>Who's this for?</h3>
</div>
<%= form_for @new_recipient, :url => scan_recipients_path do |f| %>
<div data-role="fieldcontain">
	<%= f.text_field :alias %>
</div>

<%= f.hidden_field :user_id %>
<%= f.submit('Add Someone New') %>
<%end%>

<hr></hr>
<h3 class="pagination-centered">Existing Gift Lists </h3>
<div class="pagination-centered">
	<% @recipients.each do |recipient| %>
	<% unless recipient.id.nil? %>
	<%= link_to recipient.alias,scan_recipient_path(@scan.upc, recipient.id), :method => :put, "data-role" => "button" %>	
	<%end%>
	<%end%>
</div>