config/routes.rb
NiftyGifter::Application.routes.draw do 

  resources :token, :only => [:create, :destroy]

  resources :events do 
    resources :recipients, :controller => "events"
  end

  resources :recipients do 
    get 'checkout' => 'recipients#checkout'
  end


  resources :scans do
    resources :recipients, :controller => "scans", :except => [:show] 
  end
  match '/events/new/recipient/:recipient_id' => 'events#new', :via => 'get', :as => :new_event_with_recipient
  match '/scans/find/:upc' => 'scans#find', :via => 'get'
  match '/scans/:scan_id/recipients/:id(.:format)' => 'scans#update', :via => 'get'




  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do    
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    match 'auth/:provider/callback', to: 'users/omniauth_callbacks#facebook'
    get '/login' => 'devise/sessions#new', :as => :app_root
    get '/logout' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

  def index
  	if user_signed_in?
  		@graph = Koala::Facebook::API.new(current_user.access_token)
  		render 'user_main'
  	else
  		render 'index'
  	end
  end

  def login
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">

  <style type="text/css">
  body {
    margin-top:100px;    
  }
  </style>

  <div class="hero-unit">
    <div class="row">
      <div class="span5">
        <%= image_tag "gifter_logo.png", {:size => "350x350"}%>
      </div>
      <div class="span6 pagination-right">
        <div class="spacer-20"></div>
        <a href="https://twitter.com/niftygifter1" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @niftygifter1</a>
        <div class="well" id="wufoo-z7x3p9">
          <a href="http://myniftygifter.wufoo.com/forms/z7x3p9"></a>.
        </div>
      </div>
    </div>
  </div>


  <script type="text/javascript">var z7x3p9;(function(d, t) {
    var s = d.createElement(t), options = {
      'userName':'myniftygifter', 
      'formHash':'z7x3p9', 
      'autoResize':true,
      'height':'244',
      'async':true,
      'header':'show'};
      s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
      s.onload = s.onreadystatechange = function() {
        var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
        try { z7x3p9 = new WufooForm();z7x3p9.initialize(options);z7x3p9.display(); } catch (e) {}};
        var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
      })(document, 'script');

      $(".navbar").hide();

      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

    </script>

</div>

app/views/home/user_main.html.erb


<div class="pagination-centered">
	<% unless browser.mac? %>
	<a href="http://zxing.appspot.com/scan?ret=<%= URI.encode('' << root_url << 'scans/find/{CODE}')%>">
		<img class="add-image" src=<%=image_path("scan_button.png")%>>
	</a>
	<%else%>
	<a href="pic2shop://scan?callback=<%= URI.encode('' << root_url << 'scans/find/EAN')%>">
		<img class="add-image" src=<%=image_path("scan_button.png")%>>
	</a>	
	<%end%>
</div>

<h3 class="pagination-centered"> Scan UPC </h3>
<hr></hr>
<div class="pagination-centered">
	<%= button_to "Events", events_path, :method => "get"%>
</div>
<div class="pagination-centered">
	<%= button_to "Gift Lists", recipients_path, :method => "get"%>
</div>