config/routes.rb
NiftyGifter::Application.routes.draw do 

  resources :token, :only => [:create, :destroy]

  resources :events do 
    resources :recipients, :controller => "events"
  end

  resources :recipients do 
    get 'checkout' => 'recipients#checkout'
  end


  resources :scans do
    resources :recipients, :controller => "scans", :except => [:show] 
  end
  match '/events/new/recipient/:recipient_id' => 'events#new', :via => 'get', :as => :new_event_with_recipient
  match '/scans/find/:upc' => 'scans#find', :via => 'get'
  match '/scans/:scan_id/recipients/:id(.:format)' => 'scans#update', :via => 'get'




  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do    
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    match 'auth/:provider/callback', to: 'users/omniauth_callbacks#facebook'
    get '/login' => 'devise/sessions#new', :as => :app_root
    get '/logout' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
	default_scope order('event_time desc')
	belongs_to :recipient
	has_many :users, :through => :recipient

	attr_accessible :name, :recipient_id, :reminder, :event_time, :day, :month

	accepts_nested_attributes_for :recipient

	validates_presence_of :event_time
	validates_presence_of :name, :message => "Event requires a name"
	validates_presence_of :recipient_id, :message => "Events require a valid recipient"

	def set_time
		begin
			day = self.day
			month = self.month
			date = Date.new(Time.now.year,month,day)

			if(date.past?)
				date = date.next_year
			end

			self.event_time = date
		rescue
			raise
		end
		true
	end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
	before_filter :authenticate_user! 

	def new
		@event = current_user.events.build

		begin
			@selected_recipient_id = current_user.recipients.find(params[:recipient_id]).id
		rescue 
			@selected_recipient_id = nil
		end
	end

	def update
	end

	def create
		@event = Event.new(params[:event])

		@event.set_time
		@event.save!

		send_sms(current_user,@event)

		redirect_to events_path, :notice => "Event Added"
	end

	def index
		@events = current_user.events.limit(10)
	end

	def destroy
		@event = current_user.events.find(params[:id])
		@event.destroy
		redirect_to root_path
	end

	private 
	def send_sms(user, event)
	    #temporary code until this has a permanent home w/ a scheduler
	    account_sid = ENV["TWILIO_ID"]
	    auth_token = ENV["TWILIO_AUTH"]

	    unless Rails.env.test?
	    	begin
	    		@twilio = Twilio::REST::Client.new account_sid, auth_token
	    		@account = @twilio.account
	    		@message = @account.sms.messages.create({:from => '+16122354981', :to => user.phone, 
	    			:body => "" << event.recipient.alias << "'s " << event.name << " is coming up... Visit " << recipient_url(event.recipient)  << " and buy them something!"})
	    		puts @message	
	    	rescue
	    	end
	    end	
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h3 class="pagination-centered">Upcoming Events</h3>
<%= link_to "Create New Event", new_event_path, "data-role" => "button" %>
<hr></hr>
<div class="pagination-centered">
	<% @events.each do |event| %>
	<%= link_to event.recipient.alias + " - " + event.name + " - " + event.event_time.strftime("%B %d, %Y"), 
	event_path(event), 
	"data-role" => "button"
	%> 
	<%end%>
</div>

app/views/events/new.html.erb
<div class="pagination-centered">
	<h3>Create an Event</h3>
</div>
<%= form_for @event do |f| %>

<div data-role="fieldcontain">
	<%= f.label :recipient, "Whos event?" %>
	<%= f.collection_select(:recipient_id, current_user.recipients, :id, :alias_for_collection, 
		{:selected => @selected_recipient_id}) %>
</div>

<div data-role="fieldcontain">
	<%= f.label :name, "What event?" %>
	<%= f.text_field :name %>
</div>

<div data-role="fieldcontain">
	<fieldset data-role="controlgroup" data-type="horizontal">
		<legend>Event Date</legend>
		<%= select_month(1, :prefix => "event")%>
		<%= select_day(1, :prefix => "event")%>
	</fieldset>
</div>

<div data-role="fieldcontain">
	<%= f.label :reminder, "Remind me in (days)" %>
	<%= f.select(:reminder, options_for_select([1,2,3,5,10,15,30])) %>
</div>

<%= f.submit('Create Event') %>
<%end%>

app/views/events/show.html.erb
<div class="pagination-centered">
	<h3><%= @event.name %>'s Saved Items</h3>

	<% @event.recipient.scans.limit(8).each do |scan| %>
	<% @scan = scan %>
	<%= render 'layouts/scan-list' %>
	<%end%>
</div>

<%= link_to "Purchase Items", @event.recipient.checkout_url, :method => "get", "data-role" => "button" %>

<%= render 'layouts/scan-links' %>

<%= link_to "Delete this event's wishlist",@event, 
:confirm => "Are you sure you wish to delete this person's gift list?",
:method => :delete, 
"data-ajax" => "false",
:rel => "external",
"data-role" => "button"
%>