config/routes.rb
NiftyGifter::Application.routes.draw do 

  resources :token, :only => [:create, :destroy]

  resources :events do 
    resources :recipients, :controller => "events"
  end

  resources :recipients do 
    get 'checkout' => 'recipients#checkout'
  end


  resources :scans do
    resources :recipients, :controller => "scans", :except => [:show] 
  end
  match '/events/new/recipient/:recipient_id' => 'events#new', :via => 'get', :as => :new_event_with_recipient
  match '/scans/find/:upc' => 'scans#find', :via => 'get'
  match '/scans/:scan_id/recipients/:id(.:format)' => 'scans#update', :via => 'get'




  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do    
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    match 'auth/:provider/callback', to: 'users/omniauth_callbacks#facebook'
    get '/login' => 'devise/sessions#new', :as => :app_root
    get '/logout' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

end

app/views/layouts/_ieshim.html.erb
	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]--> 

app/views/layouts/_jquery-mobile.html.erb
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
<script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
<%= stylesheet_link_tag "niftygifter-theme" %>

app/views/layouts/_landing-page.html.erb
<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "distinctive" %>

app/views/layouts/_mobile-header.html.erb
<div data-role="page" data-dom-cache="true">
	<div data-role="header" >
		<div class='ui-btn-right' style="font-size: 36px;">
			<a style="color:#FFF;text-decoration:none;" href=<%= current_user ? root_path : app_root_path %>>
				<i class="icon-home icon-large"></i> 
			</a>
		</div>
		<%= image_tag 'gifter_logo_smaller.png'%>
	</div>

	<div id="messages">		
		<% if flash[:alert] %>
		<div class = "alert alert-error" id="alert">
			<ul>
				<li><%= flash[:alert] %></li>
			</ul>
		</div>
		<% end %>
		
		<% if flash[:notice] %>
		<div class = "alert alert-error" id="notice">			
			<ul>
				<li><%= flash[:notice] %></li>
			</ul>
		</div>
		<% end %>		

		<% if defined? @user and not devise_error_messages!.blank? %>
		<div class = "alert alert-error" id="alert">
			<%= devise_error_messages! %>
		</div>
		<%end%>
	</div>

	<div data-role="content">
		<%= yield %>
	</div>

	<div data-role="navbar" data-position="fixed">
		<ul>
			<% if current_user %>
			<li>
				<a href="#" data-rel="back" data-icon="back">Back</a>
			</li>
			<li>
				<%= link_to "Edit Account", edit_user_registration_path, :method => "get", "data-icon" => "gear" %>
			</li>	
			<li>
				<%= link_to "Log Out", destroy_user_session_path, :method => :delete, "data-icon" => "back" %>
			</li>
		
			<% else %>
			<li>
				<a href="#" data-rel="back" data-icon="back">back</a>
			</li>
			<li>
				<%= link_to "Log In", new_user_session_path, "data-icon" => "check" %>
			</li>
			<li>
				<%= link_to "Sign Up", new_user_registration_path, "data-icon" => "plus"%>
			</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/layouts/_scan-links.html.erb
<!-- 	<% unless browser.mac? %>
	 <a  href="http://zxing.appspot.com/scan?ret=<%= URI.encode('' << root_url << 'scans/{CODE}')%>">
		Scan a new item
	</a>
	<%else%>
		<a href="pic2shop://scan?callback=<%= URI.encode('' << root_url << 'scans/EAN')%>">
		Scan a new item
	</a>
	<%end%> -->

app/views/layouts/_scan-list.html.erb
	<% response = @scan.get_response %>
	<div class="well" style="height:80px;">
		<div class="width-70 pull-right pagination-left">
			<a href=<%=response.items.first.get('DetailPageURL')%>/><%= response.items.first.get('ItemAttributes/Title').truncate(40)%></a> <br/>
			<strong><%= response.items.first.get('OfferSummary/LowestNewPrice/FormattedPrice')%></strong>

			<div class="pull-right">
				<%= link_to raw('<i class="icon-remove"></i>'),scan_path(@scan), 
				:confirm => "Are you sure you wish to delete this gift?",
				:method => "delete", 
				:remote => true, 
				:class=>'delete_scan' %>
			</div>
		</div>
		<div class="width-20">
			<img src=<%= response.items.first.get('SmallImage/URL')%>>	
		</div>
	</div>
	<script>
	    $('.delete_scan').bind('ajax:success', function() {  
        $(this).closest('.well').fadeOut();  
    });  
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Nifty Gifter</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Nifty Gifter helps you give the gifts they deserve and keep track of the things they want you to remember"/>
	<meta name="keywords" content="nifty gifter, wishlist, amazon, reminders, gift, present" />
	<meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Arbutus+Slab' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
	
	<%unless (request.fullpath == "/" && !user_signed_in?) %>
		<%= render 'layouts/jquery-mobile'%>
	<%else%>
		<%= render 'layouts/landing-page'%>
	<%end%>

	<%= render 'layouts/ieshim' %>
	<%= render 'layouts/analytics'%>
</head>
<body>
	<!-- load landing page -->
	<%if request.fullpath == "/" && !user_signed_in? %>
		<%= yield%>
	<%else%>
		<%= render 'layouts/mobile-header'%>
	<%end%>
</body>
</html>